### ISSUE TITLE
Impossible to change creator

### ISSUE THREAD

**Issue by tomasr78** [johnwhitington/cpdf-source#128] opened 2018-06-06 08:25 UTC
I was trying to change PDF Creator(Application) field using command below but what it does is to add another `/Creator(MyTestCreator)` into PDF file and leaves the old pdf creator intact. The Acrobat is still display old creator. Is this by design or bug?

`cpdf.exe -set-creator "MyTestCreator" in.pdf -o out.pdf`

**Comment by johnwhitington** [comment] 2018-06-06 09:44
There are two kinds of metadata, the old plain kind, which cpdf knows how to set, and the new XML kind, which it does not. So, you can either edit the XML metadata by extracting it and altering it, or use -remove-metadata if you don't mind losing it.

The next version of cpdf will allow the XML metadata to be altered also.

**Comment by tomasr78** [comment] 2018-06-06 10:45
Whe are you planing next version?

**Comment by johnwhitington** [comment] 2019-06-20 12:21
Duplicate of #139

**Closed by johnwhitington** 2019-06-20 12:21 UTC
