### ISSUE TITLE
cpdf won't process file with a badly formed page tree

### ISSUE THREAD

**Issue by berwynhoyt** [johnwhitington/cpdf-source#5] opened 2014-07-10 10:15 UTC
cpdf won't even try to process files with a badly formed page tree. For example, any file created by the [iCopy scan tool](http://icopy.sourceforge.net/):

```
> cpdf -rotateby 90 scan.pdf -o scan2.pdf
  cpdf encountered an error. Technical details follow:
  badly formed page tree B
```

For example, use [this pdf](https://docs.google.com/file/d/0B29nw-jA9R_fbU5IR29tenAtRlE/edit).

Admittedly, this is probably iCopy's fault, but it seems that cpdf should at least try to process it seeing the viewers can all display it.

**Comment by andrey-zelenin** [comment] 2016-02-03 13:34
We have the same problem on current version cpdf. Problem file [https://drive.google.com/open?id=0B-KoKs01KTskUl9LeDc5LUluNUU](url) created by the  Redmine. Maybe, this is probably Redmine fault or previous fix does not work

**Comment by johnwhitington** [comment] 2016-02-03 23:25
OS X Preview says "The file could not be opened. It may be damaged".

The file claims to have two pages, but one of them (5 0 R) just points directly to a page stream, not a page object:

```
1 0 obj
<</Type /Pages
/Kids [3 0 R 5 0 R ]
/Count 1
/MediaBox [0 0 595.28 841.89]
>>
endobj
5 0 obj
<</Length 148324
/Filter /FlateDecode
/Length1 264072
>>
stream
```

You need to remove the "5 0 R". I'm not sure how it got in there. The space after "5 0 R" seems suspicious, because the file does not otherwise contain spaces before closing square brackets.

Here's the creation data:

```
26 0 obj
<<
/Producer (TCPDF via RFPDF 1.53.0.TC031 \(http://tcpdf.sourceforge.net\))
/Title <FEFF0045004D0053004F00570020002D002000420075006700200023003100340035>
/Creator (Redmine)
/CreationDate (D:20140731024726)
>>
```

Perhaps it was processed by a second program?

We try to make cpdf deal with broken files, especially if Acrobat opens them (which it seems to here) but it's hard to see what to do with this one -- it's just so broken.

**Comment by andrey-zelenin** [comment] 2016-02-04 08:35
> OS X Preview says "The file could not be opened. It may be damaged".
I tried on Windows and no problems wih opening file.
Also tried to open in Preview on Mac no problems found. 

> Perhaps it was processed by a second program?
no, file generated by Redmine, perhaps it is problem of Redmine, I dont' know, but file looks like valid.
 I used [identify ](http://www.imagemagick.org/script/identify.php) utility from imagemagick  for checking file.

**Comment by johnwhitington** [comment] 2016-02-04 10:57
Thanks for the clarification. There's no question that the file is horribly malformed. Please open a ticket with Redmine, and link to it from this ticket.

The `identify` utility just checks the first few bytes of the file.

**Comment by andrey-zelenin** [comment] 2016-02-11 08:20
Perhaps we have old version of Redmine. We try to update it and reproduce case. I'll let you know about results. Thanks.

**Comment by johnwhitington** [comment] 2017-01-09 17:11
Any update?

**Comment by andrey-zelenin** [comment] 2017-01-10 08:02
we've updated, the problem is not reproduced, thanks

**Closed** 2017-01-10 09:54 UTC
